version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FIRST_ADMIN_USER: admin
      FIRST_ADMIN_PASSWORD: internalpassword
  redis:
    image: "redis:alpine"