name: deploy-and-run
on: 
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .ssh dir
        run: mkdir ~/.ssh
      - name: Create known hosts file
        run: touch ~/.ssh/known_hosts
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/flyffdb/content-generation/
      - name: Run content generation and image downloader
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd content-generation; php composer.phar install; php generate.php"
      - name: Stop and delete current searchserver container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker container stop searchserver; docker container rm searchserver"
      - name: Repopulate search index
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd content-generation; php populate-index.php"
      - name: Start fresh searchserver container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker run -d -v /home/flyffdb/content-generation/:/app -w /app -p 9501:9501 --name searchserver openswoole/swoole php server.php"